version: '2.0'
services:
  # Quiz Tool to be tested
  client:
    build: client
    ports:
      - "80:80"
    links:
      - server_node
    depends_on:
      - chrome
      - firefox
  server_node:
    build: server
    environment:
      - NODE_ENV=test
      - AUTH_DISABLED=true
      - GOOGLE_AUTH_DISABLED=true
    env_file:
      - .env
    links:
      - database
    depends_on:
      - chrome
      - firefox
  database:
    image: mongo
    ports:
      - "27017:27017"
    depends_on:
      - chrome
      - firefox
  # Integration tests runner
  tester:
    build: tester
    depends_on:
      - chrome
      - firefox
      - selenium-hub
    env_file:
      - .env
    entrypoint: npm test
  # Selenium hub for integration testing
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=10
      - NODE_MAX_INSTANCES=10
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=10
      - NODE_MAX_INSTANCES=10
