# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: AWS integration
          command: |
            sudo -H pip install awsebcli==1.11.18
            echo "eb version:"
            eb --version

      - run:
          name: install docker-compose
          command: |
            set -x
            sudo chown -R $(whoami) /usr/local/bin
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: docker compose build image
          command: |
            set -x
            docker-compose build
            docker-compose up -d

      - run:
          name: unit tests
          command: |
            curl localhost

      # deploy only master and develop branch
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              chmod +x scripts/deploy.sh
              ./scripts/deploy.sh
            fi
